[project]
name = "finance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.17.0",
    "aiosqlite>=0.20.0",
    "asyncpg>=0.29.0",
    "fastapi>=0.115.0",
    "httpx>=0.28.0",
    "pydantic-settings>=2.7.0",
    "pytest>=8.3.0",
    "pytest-asyncio>=0.25.0",
    "uvicorn>=0.34.0",
]

[tool.pytest.ini_options]

pythonpath = ["."]
asyncio_mode = "auto"
